### ISSUE TITLE
first website redesign team meeting

### ISSUE THREAD

**Issue by ghost** [nodejs/website-redesign#2]
let's try and schedule our first meeting, @nodejs/website-redesign. since we have members from US and EU timezones, we should aim for around 4-7pm UTC so that everyone can attend. what would be a good day/time for everyone? and what would you like to see discussed?

**Comment by maddhruv** [comment]
@pup can you also include me on the website-redesign team?

**Comment by ghost** [comment]
@maddhruv are you interested in the conception stage of the new website? i'm afraid there isn't going to be any coding or design work for a while

**Comment by fhemberger** [comment]
Some ideas for topics:

- Overall site structure
- Addressing content, which is held in separate repos (e.g. Code of Conduct, TSC members, release schedule, collaborator guidelines)
- Syncing with the Foundation website needed? (I briefly talked with @gtewallace about this)
- Is there anything missing right now?

I'm fine with 4-7pm UTC, any day is fine but Fridays tend to be a bit packed.

**Comment by amiller-gh** [comment]
I'm happy with around 4-7 UTC, and any day is fine for me except Wednesdays, but I'm unfortunately gone on a company retreat this Thursday and Friday.

To make this a bit easier on us, I've put together a Doodle poll to collect responses please fill in with your availability! Times should be in your local timezone: https://doodle.com/poll/qmzemnmr2huep7bt

**Comment by maddhruv** [comment]
> @maddhruv are you interested in the conception stage of the new website? i'm afraid there isn't going to be any coding or design work for a while

@pup include me in. I would love to help at every stage.

**Comment by franciscop** [comment]
I'm working in Japan so I am not sure I will be able to join because of the timezone (but I'll try my best).

IMHO these might fit as well for the initial meeting:

- Timeframe, availability of people, general objectives, target audience, etc. PM-like stuff.
- Decision structure. Who to consult depending on what? Anyone has a last saying on some topics? When stuck, where to ask for help?
- Previous issues and why there is no new website yet. I am really concerned about this, seeing there are many previous attempts. What is being done to fix it?

**Comment by ghost** [comment]
@bnb i can't seem to invite @maddhruv to the organization, can you take care of that?

**Comment by bnb** [comment]
@pup done :)

**Comment by jestho** [comment]
I'm probably not able to attend until February, but I would love some meeting minutes if you guys decide to have the meeting before that. Are we doing VC meetings or Slack/similar?

👍  on @franciscop point about the previous attempts.

**Comment by pierreneter** [comment]
@nodejs/website-redesign Hey everyone, should we have a place to chat quickly? The same: Slack, Discord or a Telegram group? In future, for small problems, can be resolved immediately without having to wait for meetings.
P/s: I saw a new repository: https://github.com/nodejs/i18n. I just want to mention it here because it seems to be related to us.

**Comment by ghost** [comment]
I'm going to schedule our first meeting for Thursday next week, meaning the 1st of February, at 3PM UTC. Even if not everybody is able to attend, I think as long as we take meeting notes, we should be fine.

As for a place to chat, I can set up a temporary Discord server, although this is an issue currently being discussed in the Community Committee: https://github.com/nodejs/admin/issues/53. Maybe if we adopt Discord officially, we could have a channel on that?

**Comment by ghost** [comment]
Posted the meeting issue: https://github.com/nodejs/website-redesign/issues/3

**Comment by bnb** [comment]
@pup regardless of when the meeting is, could you invite me? Thanks 🙏

**Comment by ghost** [comment]
@bnb You are invited, as you are a member of this team 😄

**Comment by bnb** [comment]
Thanks 😅

**Comment by timothyis** [comment]
Would love a discord (or slack) for node, so we can talk about the website redesign in real-time. Would be cool 👍

**Comment by bnb** [comment]
FWIW we could very easily get a channel created in the nodeslackers ([nodeslackers.com](http://nodeslackers.com)) slack team – would that work for y'all?

**Comment by ghost** [comment]
Closing this.
